import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy — creagent",
  description: "How creagent handles your data.",
};

const SECTIONS: { title: string; body: string }[] = [
  {
    title: "What we collect",
    body: "When you sign in with GitHub we receive your GitHub profile name, avatar and email. Anything you save to an account — agents, skills and settings — is stored in our Supabase database. When you use the composer signed-out, everything stays in your browser's localStorage.",
  },
  {
    title: "How we use it",
    body: "Your data exists to sign you in, keep your agents saved to your account, and serve your agents to you over MCP. The onboarding AI-assisted draft is generated by Azure AI Foundry from answers you give on that page. We do not sell your data and do not use it for advertising.",
  },
  {
    title: "Who we share it with",
    body: "Hosting and infrastructure providers that make the service run: Supabase (database and auth), Vercel (hosting), GitHub (OAuth sign-in) and Azure AI Foundry (draft generation, only when you use it). None of them may use your data for their own purposes.",
  },
  {
    title: "Cookies",
    body: "We use the cookies Supabase Auth sets to keep you signed in. No tracking, analytics or advertising cookies are set by this site.",
  },
  {
    title: "Your control",
    body: "Signed-out drafts are yours in your browser — clear your site data to delete them. Saved account data can be deleted by signing out and asking us to remove your account, or by deleting your data through the app where available.",
  },
  {
    title: "Changes",
    body: "This policy may change as the service evolves. Material changes will be announced on this page. Continued use of the service after a change means you accept the updated policy.",
  },
];

export default function PrivacyPage() {
  return (
    <div>
      <div className="mx-auto max-w-3xl px-5 py-10">
        <h1 className="font-pixel text-xs sm:text-sm mb-1">PRIVACY</h1>        <p className="mt-4 font-mono text-xs text-muted">
          Last updated: August 2026
        </p>

        <div className="mt-8 space-y-5">
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 className="font-sans font-bold text-base">{s.title}</h2>
              <p className="mt-1.5 font-mono text-xs text-ink-soft leading-relaxed">
                {s.body}
              </p>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
